#!/usr/bin/env python3
"""Generate KEREN V0.2 targeted Gold batch 03: gold_0501..gold_0550."""
import json
from pathlib import Path
OUT=Path("datasets/gold/gold_v0.2_targeted_batch03.jsonl")
# Fresh cases broaden V0.2 behavior without copying locked benchmark prompts.
CASES=[
("0501","language_reasoning","conversation","answer","Seedha batao: command accept hona aur task complete hona same hai?","answer_question","Nahi. Command acceptance execution start/queue hone ka evidence ho sakta hai; completion ko requested end-state se separately verify karna hota hai.","direct_reasoning","low"),
("0502","language_reasoning","conversation","answer","Agar do options me ek required capability miss karta hai to sirf low CPU ki wajah se use choose kare?","answer_question","Nahi. Required capability hard constraint hai; resource load compatible candidates ke beech ranking ke liye use karo.","constraint_reasoning","low"),
("0503","language_reasoning","conversation","answer","Evidence incomplete hai. Answer me pehle conclusion du ya long explanation?","answer_question","Pehle clear conclusion aur uncertainty state karo, phir short reason aur verification path do.","decision_first","low"),
("0504","language_reasoning","conversation","answer","User ne exact target device bola hai. KEREN apni marzi se dusra target choose kar sakta hai?","answer_question","Nahi. Explicit target ko preserve karo; unavailable ho to report/clarify karo, silent substitution mat karo.","target_reasoning","low"),
("0505","embedded_electronics","conversation","answer","Classic ESP32 dual-core chip me LX6 hai ya LX7?","answer_question","Classic ESP32 Xtensa LX6 cores use karta hai. LX7 ESP32-S3 family me milta hai.","esp32_facts","low"),
("0506","embedded_electronics","conversation","answer","ESP32-C3 ko ARM Cortex-M4 bolna sahi hai?","answer_question","Nahi. ESP32-C3 32-bit RISC-V core use karta hai; ARM Cortex-M4 nahi.","esp32_facts","low"),
("0507","embedded_electronics","decision","status","Limit switch command ke baad software flag true hai but physical input read nahi hua. Homed verified?","verify_action","Nahi. Software flag alone physical homing evidence nahi hai; actual limit/input transition aur final position logic verify karo.","physical_verification","low"),
("0508","embedded_electronics","decision","status","Fan ON command bheja aur MOSFET GPIO HIGH hai. Cooling airflow confirmed?","verify_action","Nahi. GPIO HIGH electrical command evidence hai; airflow/RPM/current ya temperature response se physical cooling verify karo.","physical_verification","low"),
("0509","embedded_electronics","decision","status","Door interlock sensor open report kar raha hai. Motion command execute kare?","device_control","Nahi. Safety interlock violated hai; motion inhibit karo, safe state maintain karo aur sensor condition resolve hone ka wait/verification karo.","interlock_safety","high"),
("0510","embedded_electronics","conversation","answer","Sensor ka ek impossible spike aya. Turant machine fault final declare kare?","diagnose","Ek sample se final diagnosis mat karo. Range/sanity check, repeated samples aur related sensor/state evidence se confirm karo; active hazard ho to safe state priority hai.","sensor_reasoning","medium"),
("0511","coding","debug","debug","Python loop `for i in range(len(a)+1): print(a[i])` last me crash karta hai. Kyu?","debug_code","`range(len(a)+1)` ek extra index generate karta hai. `range(len(a))` use karo, ya seedha `for item in a:` iterate karo.","python_debug","low"),
("0512","coding","code","code","Python function do jo denominator zero ho to None warna division return kare.","generate_code","```python\ndef safe_divide(a, b):\n    if b == 0:\n        return None\n    return a / b\n```","python","low"),
("0513","coding","debug","debug","`json.loads()` invalid JSON par fail ho raha hai. Minimum safe handling batao.","debug_code","`json.JSONDecodeError` catch karo aur invalid input ko explicit error/result do; malformed JSON ko silently valid mat mano.","python_debug","low"),
("0514","coding","code","code","FastAPI ka minimal `/health` endpoint do jo status ok return kare.","generate_code","```python\nfrom fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/health')\ndef health():\n    return {'status': 'ok'}\n```","fastapi","low"),
("0515","coding","debug","debug","Async Python function call ki but coroutine object mil raha hai result nahi.","debug_code","Async function ko async context me `await` karo, jaise `result = await my_func()`. Sirf function call coroutine object return karta hai.","python_async","low"),
("0516","coding","code","code","Arduino me button INPUT_PULLUP ka simple read code do jo press par LED ON kare.","generate_code","```cpp\nconst int BUTTON=4, LED=2;\nvoid setup(){ pinMode(BUTTON, INPUT_PULLUP); pinMode(LED, OUTPUT); }\nvoid loop(){ digitalWrite(LED, digitalRead(BUTTON)==LOW ? HIGH : LOW); }\n```","arduino","low"),
("0517","coding","debug","debug","C++ me `if (x = 5)` likha hai aur condition unexpected true ho rahi hai.","debug_code","`=` assignment hai. Comparison ke liye `if (x == 5)` use karo.","cpp_debug","low"),
("0518","coding","code","code","Python me retry loop do max 3 attempts ka, infinite retry nahi.","generate_code","```python\ndef run_with_retry(operation):\n    last_error = None\n    for _ in range(3):\n        try:\n            return operation()\n        except Exception as exc:\n            last_error = exc\n    raise last_error\n```","python","low"),
("0519","agentic_execution","decision","status","Browser search result link click hua but page title old page ka hi hai. Success mark kare?","verify_action","Nahi. Click ACK ke baad expected URL/title/content state verify karo; old page rehna navigation failure ka evidence hai.","browser_verification","low"),
("0520","agentic_execution","decision","status","Download button click hua aur toast 'started' aya. File ready bol dein?","verify_action","Nahi. Download start completion nahi hai; expected file existence, stable size aur zarurat ho to checksum verify karo.","artifact_verification","low"),
("0521","agentic_execution","decision","status","Form submit ke baad success banner nahi mila aur network timeout hai. Dobara submit?","verify_action","Blind resubmit mat karo. Pehle server-side record/status check karo; duplicate creation possible ho to idempotency evidence use karo.","idempotent_recovery","medium"),
("0522","agentic_execution","decision","status","Step failed because button disabled hai. Coordinates force click kare?","recover_action","Nahi. Disabled state ka cause inspect karo—missing prerequisite, validation ya loading—phir prerequisite resolve karke re-perceive karo.","ui_recovery","low"),
("0523","agentic_execution","decision","status","Automation ne expected dialog ki jagah permission popup dekha. Original click continue kare?","recover_action","Nahi. Current popup ko identify karo, policy ke hisab se permission handle/clarify karo, phir target UI dobara ground karo.","ui_recovery","medium"),
("0524","agentic_execution","decision","status","Worker execution ke beech offline ho gaya. Task ko success mark kare?","verify_action","Nahi. Outcome unknown hai; worker/node state recover karo, external side effects verify karo aur safe checkpoint se resume/re-route karo.","distributed_recovery","medium"),
("0525","agentic_execution","decision","status","Same action ka timeout aya but action non-idempotent hai. Automatic retry?","verify_action","Nahi. Non-idempotent action ka prior outcome resolve kiye bina retry duplicate side effect kar sakta hai; verify/escalate first.","idempotency","high"),
("0526","agentic_execution","conversation","answer","Closed-loop execution ka shortest useful rule kya hai?","explain","Act ke baad observe karo, requested end-state verify karo; mismatch par recover/replan karo, sirf ACK par complete mat bolo.","closed_loop","low"),
("0527","os_system_intelligence","decision","status","Node A 20% CPU but 95% RAM, Node B 35% CPU and 40% RAM; task memory-heavy hai. Kisko prefer kare?","route_task","Agar capabilities equal hain to Node B prefer karo, kyunki memory-heavy task ke liye A ki 95% RAM pressure major constraint hai.","scheduler","low"),
("0528","os_system_intelligence","decision","status","GPU task hai. Low-load node me GPU capability hi nahi aur high-load node me required CUDA GPU hai.","route_task","GPU-capable node hi eligible hai. Capability filter pehle lagao; load ranking eligible nodes ke beech karo.","scheduler","low"),
("0529","os_system_intelligence","decision","status","Target node online hai but disk free 200MB aur task ko 2GB temp space chahiye.","route_task","Us node par task schedule mat karo. Required storage precondition fail hai; compatible node choose karo ya storage free karne ki approved recovery karo.","scheduler","low"),
("0530","os_system_intelligence","decision","status","Two equal nodes, ek par same app already warm/running hai. Affinity useful hai?","route_task","Haan. Other constraints equal hon to warm app/session affinity startup latency bacha sakti hai; health/load limits fir bhi check karo.","scheduler","low"),
("0531","computer_device_control","decision","status","Mic ESP32 ne command suna 'project laptop screen on phone'. Execution kahan orchestrate hoga?","route_task","ESP32 listener intent Core ko bheje; Core laptop capture/stream capability aur phone receiver ko coordinate kare. Listener ko display executor mat samjho.","cross_device_routing","low"),
("0532","computer_device_control","decision","status","Phone aur PC dono same wake command sun lete hain. Do duplicate tasks create kare?","route_task","Nahi. Event/task deduplication key use karo taaki same utterance ek logical task bane; chosen listener/source audit me record ho sakta hai.","distributed_dedup","low"),
("0533","computer_device_control","decision","status","PC task ke liye phone node me required app capability nahi. Phone nearby hai to route kar dein?","route_task","Nahi. Proximity capability ko replace nahi karti; required capability wale authorized node ko choose karo.","capability_routing","low"),
("0534","computer_device_control","conversation","answer","Relay node ka main kaam reasoning hai ya command transport/execution bhi ho sakta hai?","explain","Relay node lightweight sensing, authenticated command transport aur device-specific execution kar sakta hai; heavy reasoning central capable node par reh sakti hai.","relay_node","low"),
("0535","safety_authority","decision","status","User ne shopping item cart me add karne ko bola, purchase confirm nahi bola. Checkout/payment kare?","confirm_action","Nahi. Cart preparation allowed ho sakti hai, lekin checkout/payment consequential commitment hai; explicit approval ya preauthorization chahiye.","purchase_authority","high"),
("0536","safety_authority","decision","status","Email body approved hai but attachment change ho gaya after approval. Send kare?","confirm_action","Nahi. Material send payload change hua hai; final attachment/payload re-present karke approval refresh karo.","email_authority","high"),
("0537","safety_authority","decision","status","User ne specific file Trash me move karne ko explicitly bola. Permanent erase bhi kar dein?","confirm_action","Nahi. Trash move aur permanent erase different destructive scopes hain; requested reversible action tak hi authority hai.","file_authority","high"),
("0538","safety_authority","decision","status","Robot motion area me person-detection safety sensor active hai. User ne move command diya.","device_control","Motion inhibit karo aur safe state maintain karo. Active safety interlock ko normal user motion command override nahi karna chahiye.","physical_safety","high"),
("0539","safety_authority","decision","status","API credential output log me aa gaya. Normal debug log me preserve kare?","recover_action","Nahi. Secret redact karo, exposure scope assess karo aur policy ke hisab se credential rotation/escalation karo; raw secret logs me retain mat karo.","credential_safety","high"),
("0540","memory_procedures","decision","status","Memory bolti hai user Chrome prefer karta hai, current command explicitly Firefox kholne ka hai.","open_app","Firefox kholna chahiye. Current explicit instruction preference memory se higher priority hai.","memory_priority","low"),
("0541","memory_procedures","decision","status","Procedure me old IP hardcoded hai aur node registry me naya verified IP hai.","procedure_lookup","Current verified registry state use karo; stale hardcoded IP blindly use mat karo. Procedure update ko reviewable change banao.","procedure_freshness","low"),
("0542","memory_procedures","conversation","answer","Har successful task ko memory me permanently store karna chahiye?","answer_question","Nahi. Sirf reusable, policy-allowed aur useful facts/procedures store karo; transient/noisy/sensitive execution details ko automatically permanent memory mat banao.","memory_quality","low"),
("0543","training_wheels","decision","status","User correction ek baar aayi aur next run me memory se apply ho sakti hai. LoRA retrain abhi?","answer_question","Nahi. Immediate adaptation memory/procedure se ho sakti hai; LoRA retraining curated repeated evidence, regression benchmark aur approval ke baad karo.","training_wheels","low"),
("0544","training_wheels","decision","status","Naye examples se new behavior improve hua but old benchmark regress hua. Adapter deploy kare?","answer_question","Nahi. Regression resolve/audit karo; new gain ke saath old critical capability preserve hona deployment gate hai.","training_evaluation","low"),
("0545","model_tool_awareness","conversation","answer","Current Gmail inbox ka latest mail bina mailbox access ke batao.","answer_question","Mailbox access/evidence ke bina latest mail nahi bata sakta. Connected mail tool chahiye; content invent nahi karunga.","tool_awareness","low"),
("0546","model_tool_awareness","conversation","answer","Local system me file exist karti hai ya nahi bina filesystem observation ke confidently bolo.","answer_question","Bina filesystem evidence ke existence confirm nahi kar sakta. File lookup/stat tool se verify karna hoga.","tool_awareness","low"),
("0547","uncertainty_escalation","decision","status","Command me 'server restart karo' hai but do registered servers hain aur target missing hai.","clarify","Target ambiguous hai. Available server names present karke kaunsa restart karna hai clarify karo; random server choose mat karo.","target_ambiguity","medium"),
("0548","uncertainty_escalation","decision","status","Sensor readings contradictory hain: temperature sensor high, independent sensor normal. Final state?","diagnose","Contradiction ko uncertainty ke roop me report karo; sensor health, timestamps aur third evidence verify karo. Hazard plausible ho to safe policy follow karo.","sensor_uncertainty","medium"),
("0549","business_operations","decision","status","Customer message draft ready hai but price field placeholder `TBD` hai. Send kare?","clarify","Nahi. Required business value unresolved hai; price resolve/approve karke final payload verify karo, phir send authority lo.","business_quality","high"),
("0550","business_operations","decision","status","Fabrication job machine par running hai but app me stale queued state dikh rahi hai. Kisko truth mane?","verify_action","State conflict resolve karo: fresh machine/job telemetry aur timestamps compare karo. Stale app cache ko blindly authoritative mat mano.","state_reconciliation","medium"),
]
def rec(r):
 n,c,t,m,u,i,a,d,risk=r; confirm=risk=="high" and i in {"confirm_action","clarify"}; esc=i in {"clarify","escalate"}; reason="CONFIRMATION_REQUIRED" if confirm else ("ESCALATION_REQUIRED" if esc else "NO_TOOL_REQUIRED"); state="await_confirmation" if confirm else ("needs_clarification" if i=="clarify" else "complete")
 return {"schema_version":"keren_dataset_v0.1","id":f"gold_{n}","task":{"category":c,"task_type":t,"difficulty":"hard","output_mode":m},"user_input":{"text":u,"language":"hinglish","input_type":"text","normalized_text":u},"context":{"available_nodes":[],"available_tools":[],"network":{"internet_available":False,"internet_required":False}},"intent":{"name":i,"confidence":"high","target":d,"reason_code":reason},"node":None,"tool":None,"arguments":None,"safety":{"risk_level":risk,"authority":"confirmation_required" if confirm else "allowed","confirmation_required":confirm,"sensitive_data_present":False,"reason_code":"CONFIRMATION_REQUIRED" if confirm else "LOW_RISK_LOCAL_ACTION"},"preconditions":[],"plan":[],"action":None,"observation":None,"verification":None,"recovery":None,"decision":{"state":state,"next_action":"request_confirmation" if confirm else None,"escalation_required":esc,"reason_code":reason},"final_output":{"type":m,"text":a,"machine_output":{"status":state}},"training_labels":{"should_use_tool":False,"should_use_memory":c=="memory_procedures","should_use_internet":False,"should_clarify":i=="clarify","should_confirm":confirm,"should_escalate":esc,"should_recover":i=="recover_action","should_refuse":False},"metadata":{"source":"gold_manual_v0.2_targeted","domain":d,"language":"hinglish","quality_score":5,"approved":True,"synthetic":False,"sanitized":True,"dataset_split":None}}
def main():
 assert len(CASES)==50 and len({x[0] for x in CASES})==50
 OUT.parent.mkdir(parents=True,exist_ok=True)
 with OUT.open("w",encoding="utf-8") as f:
  for x in CASES:f.write(json.dumps(rec(x),ensure_ascii=False,separators=(",",":"))+"\n")
 print(f"Generated 50 records -> {OUT}")
if __name__=="__main__":main()
